site_name: CTF Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: black
      accent: red
    - scheme: slate
      primary: black
      accent: red
    
repo_url: https://github.com/Rlvx/Rlvx.github.io
repo_name: Rlvx/Rlvx.github.io


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - admonition
  - def_list

plugins:
  - macros

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - assets/js/config.js
  - assets/js/matomo.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
