
site_name: CTF Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: black
      accent: red
    - scheme: slate
      primary: black
      accent: red
    
repo_url: https://github.com/Rlvx/Rlvx.github.io
repo_name: Rlvx/Rlvx.github.io
